<?php
/**
 * @file
 * story_map_handler_filter_mods_subject_hierarchicalGeographic_citySection_s.inc
 * Originally started this as a field-specific filter, but would prefer to build this as a more generic handler
 * NOTE: this file is currently not in use
 */

class story_map_handler_filter_mods_subject_hierarchicalGeographic_citySection_s extends views_handler_filter_in_operator {

  var $value_options = array(
    '1' => 'something'
    );
}
